# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false
matrix:
  include:
    - python: 3.6
    - python: 2.7
    - python: 3.6
      env:
        - CONFIG=numpy-master.ini
        - MODULES=quantities
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libgmp-dev
    - libmpfr-dev
    - ccache
cache:
  directories:
    - $HOME/.ccache
    - $HOME/.f90cache
    - $HOME/.cache/pip
install:
  - |
    set -e
    tar xzf ci/f90cache-0.96.tar.gz
    pushd f90cache-0.96
    patch -p1 < ../ci/f90cache.patch
    ./configure --prefix=$HOME/f90cache
    make install
    ln -s $HOME/f90cache/bin/f90cache $HOME/f90cache/bin/gfortran
    popd
  - export PATH=$HOME/f90cache/bin:$PATH
  - export NPY_NUM_BUILD_JOBS=4
  - pip install virtualenv
script:
  - python setup.py test
  - |
    BRANCH=`python ci/latest-maintenance-branch.py https://github.com/numpy/numpy.git`
    sed -e "s#numpy@master#numpy@$BRANCH#" < examples/numpy.ini > numpy-master.ini
  - if test -s "$CONFIG"; then python -mtestrig -g $CONFIG $MODULES; fi
notifications:
  email: false
